### PR TITLE
update typescript definitions and react-mock

### PR DESCRIPTION
**Pull request by andeee**
as an update to #13

### CODE REVIEW

**Comment by Jador** [comment]
Thanks for the PR.

So what's the point exactly for giving the props a generic type?

Also, if we added `string` to the union type for `ReactComponent` wouldn't that simplify the definition?

**Comment by andeee** [comment]
Thanks for your suggestions.

I'm still new to TypeScript and I can't speak for the author the original definitions - but I think the generic type for the props is useful for type checking the given props to the component when using the `h()` function.

I'll try to come up with a new PR once I've come up with a simpler type definition.

**Comment by arlair** [comment]
> So what's the point exactly for giving the props a generic type?

I was trying to make it compile with this:

```
    interface Props<T> {
        children?: ReactNode;
        key?: Key;
        ref?: Ref<T>;
    }
```

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts#L396

**Comment by Jador** [comment]
Thanks for the clarification.

I was looking at that yesterday and [ln 26](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts#L26) is what got me thinking about collapsing the signature by changing the union [here](https://github.com/Jador/react-hyperscript-helpers/blob/008df8177ec4a586a9e95e035aa8d4e0ff498941/generate-ts-def.js#L13).

**Comment by andeee** [comment]
I did some experiments after looking some more at react.d.ts and this is what I came up with. I compiles ok, but I think it looses some of it't type checking because of the union - it always resolves `ReactComponent<P>` to `ReactComponent<any>` so the props are'nt type checked anymore...

**Comment by andeee** [comment]
so I'm still waiting for another epiphany here ;)

**Comment by neurosnap** [comment]
closing for now

**Pull request closed without merging**
