### PR TITLE
Update TypeScript type definition generator for use with DefinitelyTyped React definition

### PR DESCRIPTION
**Pull request by arlair**
Add <P> parameter as generic type to conform to compile with React DefinitelyTyped definition

### CODE REVIEW

**Comment by Jador** [comment]
Would you check into why the test are failing now?

**Comment by arlair** [comment]
Looks like I just duplicated what @andeee wrote a day ago.

**Comment by Jador** [comment]
lol it happens. Seems like he had some epiphany so let's give it a few days to see what he comes up with.

**Comment by neurosnap** [comment]
closing for now

**Pull request closed without merging**
